# Generated by Django 2.2.3 on 2019-07-30 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Имя')),
                ('phone', models.DecimalField(blank=True, decimal_places=0, default='8-999-999-9999', max_digits=18, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(default='example@domain.com', max_length=128, verbose_name='Емейл')),
                ('subject', models.CharField(blank=True, max_length=64, null=True, verbose_name='Тема обращения')),
                ('message', models.TextField(blank=True, default=None, max_length=256, null=True, verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Обращение клиента',
                'verbose_name_plural': 'Обращения клиентов',
            },
        ),
    ]
