# Generated by Django 2.2.3 on 2019-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='phone',
            field=models.CharField(blank=True, default='8-999-999-9999', max_length=19, null=True, verbose_name='Номер телефона'),
        ),
    ]
