# Generated by Django 2.2.3 on 2019-07-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.DecimalField(blank=True, decimal_places=0, default='64', max_digits=10, null=True, verbose_name='Память устройства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Наличие товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='Наименование', max_length=128, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStatus', verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='Имя категории', max_length=128, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Фотографии товара'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная?'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Обложка товара'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия фото'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='name',
            field=models.CharField(default='Статус', max_length=128, verbose_name='Статус товара'),
        ),
    ]
