# Generated by Django 2.2.3 on 2019-07-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190728_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sales',
            field=models.BooleanField(default=False, verbose_name='Лучшие продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.DecimalField(blank=True, decimal_places=0, default='64', max_digits=10, null=True, verbose_name='Память устройства (Гб)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='iPhone', max_length=128, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена товара (RUB)'),
        ),
    ]
