# Generated by Django 2.2.3 on 2019-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190729_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Артикул товара'),
        ),
    ]
