# Generated by Django 2.2.3 on 2019-08-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_vendor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
    ]
