# Generated by Django 2.2.3 on 2019-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_vendor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name': 'Статус товара', 'verbose_name_plural': 'Статус товара'},
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи'),
        ),
    ]
